// Cursor Community Events Data
// Based on events from https://luma.com/cursorcommunity

const eventsData = [
    {
        id: 1,
        title: "Cursor Meetup Phoenix",
        city: "Phoenix",
        country: "United States",
        state: "Arizona",
        address: "1305 W Auto Dr",
        lat: 33.4484,
        lng: -112.0740,
        status: "upcoming",
        date: "2024-02-15",
        organizers: ["Sahil Dhansinghani", "Joe Previte"],
        attendees: 66
    },
    {
        id: 2,
        title: "Cursor Community Meetup Cologne",
        city: "Cologne",
        country: "Germany",
        address: "InnoDom Cologne",
        lat: 50.9375,
        lng: 6.9603,
        status: "upcoming",
        date: "2024-02-20",
        organizers: ["Teoman Köse"],
        attendees: 31
    },
    {
        id: 3,
        title: "Cafe Cursor Taipei",
        city: "Taipei",
        country: "Taiwan",
        address: "Songshan District, Taipei City",
        lat: 25.0330,
        lng: 121.5654,
        status: "upcoming",
        date: "2024-02-25",
        organizers: ["Ling Wu 吳冠霖", "Zeabur"],
        attendees: 167,
        waitlist: true
    },
    {
        id: 4,
        title: "Cursor Meetup Vadodara",
        city: "Vadodara",
        country: "India",
        state: "Gujarat",
        lat: 22.3072,
        lng: 73.1812,
        status: "upcoming",
        date: "2024-03-01",
        organizers: ["shrey shah"],
        attendees: 94,
        nearCapacity: true
    },
    {
        id: 5,
        title: "Cursor Meetup Chiang Mai",
        city: "Chiang Mai",
        country: "Thailand",
        address: "Amphoe Mueang Chiang Mai, Chang Wat Chiang Mai",
        lat: 18.7883,
        lng: 98.9853,
        status: "upcoming",
        date: "2024-03-05",
        organizers: ["Tee S.", "Digital Nomads Thailand"],
        attendees: 56
    },
    {
        id: 6,
        title: "Cafe Cursor Tashkent",
        city: "Tashkent",
        country: "Uzbekistan",
        address: "Тоshkent, Toshkent",
        lat: 41.2995,
        lng: 69.2401,
        status: "upcoming",
        date: "2024-03-10",
        organizers: ["Nick Shilov", "Roma Luev"],
        attendees: 304,
        waitlist: true
    },
    {
        id: 7,
        title: "Cafe Cursor Chennai",
        city: "Chennai",
        country: "India",
        state: "Tamil Nadu",
        lat: 13.0827,
        lng: 80.2707,
        status: "upcoming",
        date: "2024-03-12",
        organizers: ["Rahul Pattamatta", "Sanjeed"]
    },
    {
        id: 8,
        title: "Cursor Kenya Workshop",
        city: "Nairobi",
        country: "Kenya",
        address: "Nairobi, Nairobi County",
        lat: -1.2921,
        lng: 36.8219,
        status: "upcoming",
        date: "2024-03-15",
        organizers: ["Felix Jumason"],
        attendees: 19
    },
    {
        id: 9,
        title: "Cursor Meetup Riyadh",
        city: "Riyadh",
        country: "Saudi Arabia",
        address: "RRQB3536, 3536 Prince Saud Ibn Abdullah Ibn Jalawi",
        lat: 24.7136,
        lng: 46.6753,
        status: "upcoming",
        date: "2024-03-18",
        organizers: ["Dal | دال", "Mazen"],
        attendees: 49
    },
    {
        id: 10,
        title: "Cafe Cursor Florianopolis",
        city: "Florianópolis",
        country: "Brazil",
        address: "Passeio Primavera",
        lat: -27.5954,
        lng: -48.5480,
        status: "upcoming",
        date: "2024-03-20",
        organizers: ["Christian Rios", "Alexandre Ferrari"],
        attendees: 85,
        waitlist: true
    },
    {
        id: 11,
        title: "Build with Cursor: Stockholm",
        city: "Stockholm",
        country: "Sweden",
        lat: 59.3293,
        lng: 18.0686,
        status: "upcoming",
        date: "2024-03-22",
        organizers: ["Eric Zakariasson", "jonathan ljungek"]
    },
    {
        id: 12,
        title: "Cursor Meetup Bishkek",
        city: "Bishkek",
        country: "Kyrgyzstan",
        lat: 42.8746,
        lng: 74.5698,
        status: "upcoming",
        date: "2024-03-25",
        organizers: ["Nur Bazylbek"]
    },
    {
        id: 13,
        title: "Cursor Office Hours Stockholm",
        city: "Stockholm",
        country: "Sweden",
        address: "Stockholm, Stockholm County",
        lat: 59.3293,
        lng: 18.0686,
        status: "upcoming",
        date: "2024-03-28",
        organizers: ["Eric Zakariasson", "Ryan Sudhakaran", "Erik Nilsson"]
    },
    {
        id: 14,
        title: "Cursor Meetup Yerevan",
        city: "Yerevan",
        country: "Armenia",
        address: "COWO",
        lat: 40.1792,
        lng: 44.4991,
        status: "upcoming",
        date: "2024-04-01",
        organizers: ["Elmira Avagyan", "Tigran"],
        attendees: 145,
        waitlist: true
    },
    {
        id: 15,
        title: "Cursor Workshop Cebu",
        city: "Cebu",
        country: "Philippines",
        address: "Cebu City, Central Visayas",
        lat: 10.3157,
        lng: 123.8854,
        status: "upcoming",
        date: "2024-04-05",
        organizers: ["Dante"],
        attendees: 7
    },
    {
        id: 16,
        title: "Cafe Cursor Da Nang",
        city: "Da Nang",
        country: "Vietnam",
        address: "Hải Châu, Đà Nẵng",
        lat: 16.0544,
        lng: 108.2022,
        status: "upcoming",
        date: "2024-04-08",
        organizers: ["Keith Vaughan"],
        attendees: 29
    },
    {
        id: 17,
        title: "Cafe Cursor Madrid",
        city: "Madrid",
        country: "Spain",
        address: "Madrid, Comunidad de Madrid",
        lat: 40.4168,
        lng: -3.7038,
        status: "upcoming",
        date: "2024-04-12",
        organizers: ["Felipe Basurto", "gon", "David Gomes"],
        attendees: 155
    },
    {
        id: 18,
        title: "Cursor Meetup Bariloche",
        city: "Bariloche",
        country: "Argentina",
        address: "Open Work Bariloche - Espacio de Coworking",
        lat: -41.1335,
        lng: -71.3103,
        status: "upcoming",
        date: "2024-04-15",
        organizers: ["Alonso Arias"],
        attendees: 6
    },
    {
        id: 19,
        title: "Cafe Cursor Aracaju",
        city: "Aracaju",
        country: "Brazil",
        address: "Art In Coffee Club",
        lat: -10.9092,
        lng: -37.0678,
        status: "upcoming",
        date: "2024-04-18",
        organizers: ["Hugo Doria"]
    },
    {
        id: 20,
        title: "Cafe Cursor Novi Sad",
        city: "Novi Sad",
        country: "Serbia",
        address: "Novi Sad, Vojvodina",
        lat: 45.2671,
        lng: 19.8335,
        status: "upcoming",
        date: "2024-04-20",
        organizers: ["Aleksandar Hadžibabić"],
        attendees: 6
    },
    // Past events (examples - you can add more based on actual past events)
    {
        id: 21,
        title: "Cursor Meetup San Francisco",
        city: "San Francisco",
        country: "United States",
        state: "California",
        lat: 37.7749,
        lng: -122.4194,
        status: "past",
        date: "2024-01-15",
        organizers: ["Cursor Team"]
    },
    {
        id: 22,
        title: "Cursor Workshop London",
        city: "London",
        country: "United Kingdom",
        lat: 51.5074,
        lng: -0.1278,
        status: "past",
        date: "2024-01-20",
        organizers: ["Cursor Team"]
    },
    {
        id: 23,
        title: "Cafe Cursor Tokyo",
        city: "Tokyo",
        country: "Japan",
        lat: 35.6762,
        lng: 139.6503,
        status: "past",
        date: "2024-01-25",
        organizers: ["Cursor Team"]
    }
];

